apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: username0159/lab1_vault:latest
        ports:
        - containerPort: 8200