apiVersion: v1
kind: Service              
metadata:
  name: serv-lab2
spec:
  type: LoadBalancer       
  ports:
  - port: 3000
    protocol: TCP          
    targetPort: 3000
  selector:                
    app: lab2       